update (#1)
* fix boost library order

When statically compiling icinga2 with a local boost the order of the boost libraries matters.
Correcting the order fixes the following linker issue:

```
make[5]: Entering directory `.../icinga2/icinga2-2.11.3/build'
[ 98%] Linking CXX executable ../Bin/RELEASE/icinga2
.../boost_1_72_0/lib/libboost_coroutine.a(coroutine_context.o): In function `boost::coroutines::detail::coroutine_context::coroutine_context(void (*)(boost::context::detail::transfer_t), boost::coroutines::detail::preallocated const&)':
coroutine_context.cpp:(.text+0x59): undefined reference to `make_fcontext'
.../boost_1_72_0/lib/libboost_coroutine.a(coroutine_context.o): In function `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)':
coroutine_context.cpp:(.text+0xe8): undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make[5]: *** [Bin/RELEASE/icinga2] Error 1
```

Signed-off-by: Sven Nierlein <sven@nierlein.de>

* #7735 API-Event StateChange & CheckResult: Added acknowledgement and downtime_depth

* docs: better instructions for installing wixtoolset on Windows

If you try to follow the existing instructions, you might be greeted by
a long and useless error message when installing this which boils down
to the fact that the DotNet3.5 Chocolatey package actually requires a
reboot but does not properly ask for it. Enable-WindowsOptionalFeature
basically does the same as the Chocolatey package would do, but nicely
asks for a reboot after which the Chocolatey package can be installed
(which basically is a noop then) properly.

Co-authored-by: Sven Nierlein <sven@nierlein.de>
Co-authored-by: Fabian Röhl <mail@fabian-roehl.de>
Co-authored-by: Julian Brost <julian.brost@icinga.com>
Co-authored-by: Alexander Aleksandrovič Klimov <alexander.klimov@icinga.com>